Add optional arguments to to_pandas and flatten
palmb/fancy-collections pull request #2
Opened 2024-03-12 10:22 UTC by schaefed

In order to represent compound flags in `saqc` using instances of `DictOfSeries`/`DictOfPandas` instead of `DataFrames` we need a bit more flexibility in the `to_pandas` machinery. This is implemented here.

2024-03-12 11:27 UTC, palmb commented
As i understand this, you have some need for a different name schema than the default schema (`{df-name}_{column}`). 
The scheme you present is very specific to your case and i would like you to consider a simple renaming after a `squeeze`/`to_pandas`.     

If you wish for more flexibility for the column naming, we could add a `columns` keyword to the functions in question, that takes a pandas index, to which the new columns are (re)named (this would even allow duplicate column-names) in the process of flattening.  

Finally i find the word `squeeze` misleading, because IMO nothing gets squeezed.

2024-03-12 11:58 UTC, palmb commented
sorry i misunderstand your request. 

i'm fine with the multiindex approach, but would like the keyword to be renamed and default to `multiindex: bool = False`.

2024-03-12 12:47 UTC, palmb requested changes

2024-03-12 12:47 UTC, palmb commented on fancy_collections/formatting.py
> +
- [ ]  this must be merged after #1

2024-03-12 13:35 UTC, schaefed commented on fancy_collections/formatting.py
> +
> i'm fine with the multiindex approach, but would like the keyword to be renamed and default to multiindex: bool = False.

Fine with that!

2024-03-12 14:58 UTC, schaefed commented on fancy_collections/formatting.py
> +
Done!

2024-03-28 09:32 UTC, palmb commented
unfortunately we have merge conflicts. Could you fix them and ping me again ?

2024-04-03 08:31 UTC, merged